db_base: &db_base
  adapter: postgresql
  encoding: utf-8
  host: localhost
  username: l2bay
  password: <%= APP_CONFIG['db_password'] %>

<% %w(development test production).each do |env| %>
<%= env %>:
  <<: *db_base
  database: l2bay_<%= env %>
  game:
    <<: *db_base
    database: l2bay_game_<%= env %>
<% end %>
