db_base: &db_base
  adapter: postgresql
  encoding: utf-8
  username: l2bay
  pool: 5

<% %w(development test production).each do |env| %>
<%= env %>:
  <<: *db_base
  database: l2bay_<%= env %>
  <% if env == 'production' %>
  password: <%= APP_CONFIG['db_password'] %>
  <% end %>

game_<%= env %>:
  <<: *db_base
  database: l2bay_game_<%= env %>
  <% if env == 'production' %>
  password: <%= APP_CONFIG['db_password'] %>
  <% end %>
<% end %>
