development: &defaults
  sphinx_api:
    - [ localhost, 9312 ]
  # sphinxql:
  #   - 
  #     :host: localhost
  #     :port: 3313

production:
  <<: *defaults

staging:
  <<: *defaults

test:
  <<: *defaults
